from enum import Enum

class ScriptFamily(str, Enum):
    ALPHABETIC = "alphabetic"
    CONTINUOUS = "continuous"
    ABJAD = "abjad"
    BRAHMIC = "brahmic"

class CorpusRegistry:
    hits: int
    misses: int
    evictions: int
    def resize(self, limit: int) -> None: ...
    def discard(self, repository: str, abbreviation: str | None = ...) -> None: ...

def casefold_text(text: str) -> str: ...
def classify_text(text: str) -> ScriptFamily: ...
def fold_marks(text: str) -> str: ...
def shared_registry() -> CorpusRegistry: ...
